### ISSUE TITLE
Desenvolver protótipo visual

### ISSUE THREAD

**Issue by yamillesantos** [YvesCesar/morada_dos_pets#1]
Projetar wireframes de média fidelidade, para exibir de forma visual a estrutura do site Morada dos Pets

**Comment by yamillesantos** [comment]
Link do figma para acompanhar o processo de criação dos wireframes https://www.figma.com/file/TXD42QIFO0hlFUbgBy327j/Morada-dos-Pets?node-id=6%3A2&t=l8kLGq4lQlRqfRoi-1

**Comment by YvesCesar** [comment]
Protótipo finalizado :smile:
